# Generated by Django 5.1.2 on 2025-03-26 19:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relecloud", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comunidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="destination",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="destinations/"),
        ),
        migrations.AlterField(
            model_name="destination",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name="Cruise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(max_length=2000)),
                (
                    "destinations",
                    models.ManyToManyField(
                        related_name="cruises", to="relecloud.destination"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InfoRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("notes", models.TextField(max_length=2000)),
                (
                    "cruise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="relecloud.cruise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pueblo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("ubicacion", models.CharField(max_length=255)),
                ("habitantes", models.IntegerField()),
                ("descripcion", models.TextField()),
                ("servicios", models.TextField()),
                ("actividades", models.TextField()),
                ("incentivos", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="destinations/"),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "comunidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pueblos",
                        to="relecloud.comunidad",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(default="Anonymus", max_length=255)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cruise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="relecloud.cruise",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="relecloud.destination",
                    ),
                ),
                (
                    "pueblo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="relecloud.pueblo",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
