# Generated by Django 5.1.2 on 2025-03-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relecloud", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatgroup",
            name="group_name",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
