# Generated by Django 5.1.2 on 2024-10-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relecloud", "0002_cruise_inforequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cruise",
            name="destinations",
            field=models.ManyToManyField(
                related_name="cruise", to="relecloud.destination"
            ),
        ),
    ]
