# Generated by Django 5.1.2 on 2025-03-28 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("relecloud", "0002_chatgroup_groupmensajes"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GroupMensajes",
            new_name="GroupMessage",
        ),
        migrations.RenameField(
            model_name="chatgroup",
            old_name="Nombre_Grupo",
            new_name="group_name",
        ),
    ]
