# Generated by Django 5.1.2 on 2025-03-28 17:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("relecloud", "0003_rename_groupmensajes_groupmessage_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="groupmessage",
            old_name="autor",
            new_name="author",
        ),
    ]
