# Generated by Django 5.1.2 on 2025-03-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "relecloud",
            "0005_usuario_groups_usuario_is_active_usuario_is_staff_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
