# Generated by Django 5.1.2 on 2024-12-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relecloud", "0005_alter_cruise_destinations_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
