# Generated by Django 5.1.2 on 2025-03-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relecloud", "0007_review_author_alter_cruise_destinations_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("lugar_residencia", models.CharField(max_length=150)),
            ],
        ),
    ]
