# Generated by Django 5.1.2 on 2025-03-28 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relecloud", "0007_alter_groupmessage_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="pueblo",
            name="gestor",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pueblo_gestionado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="is_gestor",
            field=models.BooleanField(default=False),
        ),
    ]
