# Generated by Django 5.1.2 on 2025-03-29 04:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relecloud", "0008_pueblo_gestor_usuario_is_gestor"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatgroup",
            name="users_online",
            field=models.ManyToManyField(
                blank=True, related_name="online_in_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
