# Generated by Django 5.1.2 on 2025-03-01 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("relecloud", "0008_usuario"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario",
            old_name="nombre",
            new_name="name",
        ),
    ]
