# Generated by Django 5.1.2 on 2025-03-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relecloud", "0009_rename_nombre_usuario_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="lugar_residencia",
        ),
        migrations.AddField(
            model_name="usuario",
            name="password",
            field=models.CharField(default="password123", max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
