# Generated by Django 5.1.2 on 2025-03-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relecloud", "0009_rename_nombre_usuario_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="lugar_residencia",
        ),
        migrations.AddField(
            model_name="usuario",
            name="password",
            field=models.CharField(default="12345", max_length=128),
            preserve_default=False,
        ),
    ]
