# Generated by Django 5.1.2 on 2025-03-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0010_remove_usuario_lugar_residencia_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
