# Generated by Django 5.1.2 on 2025-03-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0013_alter_usuario_options_remove_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pueblos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pueblos/')),
            ],
        ),
    ]
