# Generated by Django 5.1.2 on 2025-05-04 16:22

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relecloud", "0014_alter_tareamudanza_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cruise",
            name="destinations",
        ),
        migrations.RemoveField(
            model_name="review",
            name="cruise",
        ),
        migrations.RemoveField(
            model_name="review",
            name="destination",
        ),
        migrations.AlterField(
            model_name="chatgroup",
            name="group_name",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True
            ),
        ),
        migrations.DeleteModel(
            name="InfoRequest",
        ),
        migrations.DeleteModel(
            name="Cruise",
        ),
        migrations.DeleteModel(
            name="Destination",
        ),
    ]
