# Generated by Django 5.1.2 on 2025-03-15 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0015_usuario_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPueblo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='pueblos/')),
            ],
        ),
        migrations.CreateModel(
            name='Pueblo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('ubicacion', models.CharField(max_length=255)),
                ('habitantes', models.IntegerField()),
                ('valoracion', models.FloatField()),
                ('num_valoraciones', models.IntegerField(default=0)),
                ('descripcion', models.TextField()),
                ('servicios', models.TextField()),
                ('actividades', models.TextField()),
                ('incentivos', models.TextField()),
                ('imagenes', models.ManyToManyField(related_name='pueblo_imagenes', to='relecloud.imagenpueblo')),
            ],
        ),
        migrations.DeleteModel(
            name='Pueblos',
        ),
        migrations.AddField(
            model_name='imagenpueblo',
            name='pueblo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_relacionadas', to='relecloud.pueblo'),
        ),
    ]
