# Generated by Django 5.1.2 on 2025-03-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relecloud", "0016_imagenpueblo_pueblo_delete_pueblos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pueblo",
            name="comunidad",
            field=models.CharField(default="nose", max_length=50),
            preserve_default=False,
        ),
    ]
