# Generated by Django 5.1.2 on 2025-03-15 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relecloud", "0017_pueblo_comunidad"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pueblo",
            name="imagenes",
        ),
        migrations.RemoveField(
            model_name="pueblo",
            name="num_valoraciones",
        ),
        migrations.RemoveField(
            model_name="pueblo",
            name="valoracion",
        ),
        migrations.AddField(
            model_name="pueblo",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="destinations/"),
        ),
        migrations.AddField(
            model_name="review",
            name="pueblo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="relecloud.pueblo",
            ),
        ),
        migrations.DeleteModel(
            name="ImagenPueblo",
        ),
    ]
