# Generated by Django 5.1.2 on 2025-03-15 21:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("relecloud", "0018_remove_pueblo_imagenes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pueblo",
            old_name="nombre",
            new_name="name",
        ),
    ]
