# Generated by Django 5.1.2 on 2025-03-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relecloud", "0019_rename_nombre_pueblo_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comunidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
