# Generated by Django 5.1.2 on 2025-03-16 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relecloud", "0020_comunidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pueblo",
            name="comunidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pueblos",
                to="relecloud.comunidad",
            ),
        ),
    ]
