# Generated by Django 5.1.2 on 2025-05-14 00:24

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relecloud", "0020_alter_chatgroup_group_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="foto_perfil",
            field=models.ImageField(
                default="fotos_perfil/default.jpg", null=True, upload_to="fotos_perfil/"
            ),
        ),
        migrations.AlterField(
            model_name="chatgroup",
            name="group_name",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="pueblo",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="destinations/"),
        ),
    ]
