# Generated by Django 5.1.2 on 2025-03-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relecloud", "0021_alter_pueblo_comunidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pueblo",
            name="comunidad",
            field=models.CharField(max_length=255),
        ),
    ]
