# Generated by Django 5.1.2 on 2025-03-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relecloud", "0023_alter_pueblo_comunidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="pueblo",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
