# Generated by Django 5.1.2 on 2025-05-14 20:19

import cloudinary.models
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relecloud", "0027_alter_chatgroup_group_name_alter_usuario_foto_perfil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatgroup",
            name="group_name",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="foto_perfil",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="default_nmvxxt",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
    ]
